
on:
 push:
  branch:
   - master







jobs:
 bulid:
  runs-on: windows
steps:
- uses: actions/checkout@v3
-  name: "login to Docker hub"
     run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}




