on:
 push:
  branch:
   - master







jobs:
bulid:
runs-on: windows
steps:
- uses: actions/checkout@v3
- name: "login to docker hub"
run: docker login --username${{DOCKER_USERNAME}} --password ${{DOCKER_PASSWORD}}




